# fly.toml app configuration file generated for foodsuggestionbot on 2023-09-27T19:15:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foodsuggestionbot"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
